config:
  base: static/tmp/
  compress: true
  csv:
    columns:
    - x
    - y
    - z
    compress: true
    delimiter: ','
    header: 1
  file: configuration.json
  inputPath: ''
  modelFileVtk: model.vts
  outputPath: ''
  shapePath: ''
globals:
  defaultPath: ../static/demo/
  uploadPath: ../static/tmp/
gui:
  partitionColor:
    color:
    - '#ffffff'
    - '#1f77b4'
    - '#aec7e8'
    - '#ff7f0e'
    - '#ffbb78'
    - '#2ca02c'
    - '#98df8a'
    - '#d62728'
    - '#ff9896'
    partition:
    - all
    - default
    - layer-4
    - layer-3
    - layer-2
    - layer-1
    - fracture3
    - fracture1
    - fracture2
    show:
    - false
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
  surfaceColor:
    color:
    - '#8c564b'
    - '#c49c94'
    - '#e377c2'
    - '#f7b6d2'
    - '#7f7f7f'
    - '#c7c7c7'
    - '#bcbd22'
    - '#dbdb8d'
    show:
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    surface:
    - fracture1
    - layer-1
    - layer-2
    - lateralmask
    - layer-3
    - layer-4
    - fracture2
    - fracture3
model:
  3d: true
  cellNumberX: 50
  cellNumberY: 50
  cellNumberZ: 50
  cornerPoint1:
  - 0.0
  - 0.0
  - 0.0
  cornerPoint2:
  - 5.0
  - 0.0
  - 0.0
  dimension:
  - 5.0
  - 10.0
  - 10.0
  discretisationType: d
  discretisationX:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  discretisationY:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  discretisationZ:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  partitionId:
    all: 0
    default: 1
    fracture1: 7
    fracture2: 8
    fracture3: 6
    layer-1: 5
    layer-2: 4
    layer-3: 3
    layer-4: 2
  structureRank:
    fracture1: 17
    fracture2: 5
    fracture3: 19
    layer-1: 4
    layer-2: 8
    layer-3: 12
    layer-4: 16
  structureWidth:
    fracture1: 0.5
    fracture2: 4.0
    fracture3: 2.0
partitionColor:
- Id: 0
  Partition: all
  Show: false
  color: '#ffffff'
- Id: 1
  Partition: default
  Show: false
  color: '#1f77b4'
- Id: 2
  Partition: layer-4
  Show: false
  color: '#aec7e8'
- Id: 3
  Partition: layer-3
  Show: false
  color: '#ff7f0e'
- Id: 4
  Partition: layer-2
  Show: false
  color: '#ffbb78'
- Id: 5
  Partition: layer-1
  Show: true
  color: '#2ca02c'
- Id: 6
  Partition: fracture3
  Show: true
  color: '#98df8a'
- Id: 7
  Partition: fracture1
  Show: true
  color: '#d62728'
- Id: 8
  Partition: fracture2
  Show: true
  color: '#ff9896'
run: false
structure:
  extension:
  - .csv
  - .csv
  - .csv
  - .asc
  - .csv
  - .csv
  - .csv
  - .csv
  file:
  - fracture1.csv
  - layer-1.csv
  - layer-2.csv
  - lateralmask.asc
  - layer-3.csv
  - layer-4.csv
  - fracture2.csv
  - fracture3.csv
  type:
  - fault
  - layer
  - layer
  - mask
  - layer
  - layer
  - fault
  - fault
surfaceColor:
- Id: '7'
  Show: true
  Surface: fracture1
  color: '#8c564b'
- Id: '5'
  Show: true
  Surface: layer-1
  color: '#c49c94'
- Id: '4'
  Show: true
  Surface: layer-2
  color: '#e377c2'
- Id: '-'
  Show: true
  Surface: lateralmask
  color: '#f7b6d2'
- Id: '3'
  Show: true
  Surface: layer-3
  color: '#7f7f7f'
- Id: '2'
  Show: true
  Surface: layer-4
  color: '#c7c7c7'
- Id: '8'
  Show: true
  Surface: fracture2
  color: '#bcbd22'
- Id: '6'
  Show: true
  Surface: fracture3
  color: '#dbdb8d'
