config:
  base: static/tmp/
  compress: true
  csv:
    columns:
    - x
    - y
    - z
    compress: true
    delimiter: ','
    header: 1
  file: configuration.json
  inputPath: ''
  modelFileVtk: model.vts
  outputPath: ''
  shapePath: ''
globals:
  defaultPath: ../static/demo/
  uploadPath: ../static/tmp/
gui:
  partitionColor:
    color:
    - '#ffffff'
    - '#1f77b4'
    - '#aec7e8'
    - '#ff7f0e'
    - '#ffbb78'
    - '#2ca02c'
    - '#98df8a'
    - '#d62728'
    - '#ff9896'
    partition:
    - all
    - default
    - layer-4
    - layer-3
    - layer-2
    - layer-1
    - fracture3
    - fracture1
    - fracture2
    show:
    - false
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
  surfaceColor:
    color:
    - '#8c564b'
    - '#c49c94'
    - '#e377c2'
    - '#f7b6d2'
    - '#7f7f7f'
    - '#c7c7c7'
    - '#bcbd22'
    - '#dbdb8d'
    show:
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    - true
    surface:
    - layer-1
    - layer-2
    - lateralmask
    - layer-3
    - layer-4
    - fracture1
    - fracture2
    - fracture3
model:
  3d: true
  cellNumberX: 50
  cellNumberY: 50
  cellNumberZ: 50
  cornerPoint1:
  - 0.0
  - 0.0
  - 0.0
  cornerPoint2:
  - 5.0
  - 0.0
  - 0.0
  dimension:
  - 5.0
  - 10.0
  - 10.0
  discretisationType: d
  discretisationX:
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  discretisationY:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  discretisationZ:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  - .nan
  partitionId:
    all: 0
    default: 1
    fracture1: 7
    fracture2: 8
    fracture3: 6
    layer-1: 5
    layer-2: 4
    layer-3: 3
    layer-4: 2
  structureRank:
    fracture1: 17
    fracture2: 5
    fracture3: 21
    layer-1: 4
    layer-2: 8
    layer-3: 12
    layer-4: 16
  structureWidth:
    fracture1: 0.2
    fracture2: 0.2
    fracture3: 0.2
run: false
structure:
  extension:
  - .csv
  - .csv
  - .asc
  - .csv
  - .csv
  - .csv
  - .csv
  - .csv
  file:
  - layer-1.csv
  - layer-2.csv
  - lateralmask.asc
  - layer-3.csv
  - layer-4.csv
  - fracture1.csv
  - fracture2.csv
  - fracture3.csv
  type:
  - layer
  - layer
  - mask
  - layer
  - layer
  - fault
  - fault
  - fault
